name: Update POM and Dockerfile

on:
  push:
    branches:
      - 'new'  # This will trigger on push to any branch. Modify to specific branches if needed (e.g., 'main', 'feature/*')
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python you want to use (e.g., '3.10')

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      # Step 4: Run the Python script
      - name: Run update script
        run: python updateVersionsPOMDocker.py  # Replace with the path to your script

      # Step 5: Commit and push changes (if needed)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml Dockerfile
          git commit -m "Update versions in pom.xml and Dockerfile" || echo "No changes to commit"
          git push origin $GITHUB_REF  # Ensure the changes are pushed to the same branch
